name: test

on:
  push:
    branches:
      - 'master'
      - 'develop'
    tags:
      - 'v*.*.*'
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version:
          - '1.23'
          - '1.22'
          - '1.21'
          - '1.20'
          - '1.19'
          - '1.18'
          - '1.17'
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    env:
      GO111MODULE: 'on'
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install dependencies
        run: go get .
      - name: Test with the Go CLI
        run: go test ./...
